apiVersion: v2
name: foreman
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: foreman
  version: "*.*.*"
- name: pulpcore
  version: "*.*.*"
- name: redis
  version: 16.13.2
  repository: https://charts.bitnami.com/bitnami
  condition: redis.install
