# Default values for foreman-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  redis:
    auth:
      enabled: true
      # secret:
      # key:
    # host: redis.hostedsomewhere.else
    # port: 6379
    # user: webservice
    # sentinels:
    #   - host:
    #     port:
    sentinelAuth:
      enabled: false
      # secret:
      # key:

## Configuration of Redis
redis:
  install: true
  auth:
    existingSecret: foreman-redis-secret
    existingSecretKey: redis-password
    usePasswordFiles: true
  architecture: standalone
  cluster:
    enabled: false
  metrics:
    enabled: true
