kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  {{- if .Release.IsInstall }}
  database_fields.symmetric.key: {{ randAlphaNum 32 | b64enc }}
  {{- else }}
  database_fields.symmetric.key: {{ index (lookup "v1" "Secret" $.Release.Namespace (include "fullname" .)).data "database_fields.symmetric.key" }}
  {{- end }}